### PR TITLE
Added more testing snippets for Ultisnips

### PR DESCRIPTION
**Pull request by andrewstuart**
I added a few test-specific angular directives, and one for promises using the $q(function()) syntax. Stuff I end up using alot, so hopefully it's helpful :-)

### CODE REVIEW

**Comment by matthewsimo** [comment]
Thanks for submitting a pull request, I'll review tonight!

**Comment by andrewstuart** [comment]
You may notice when you check things out that the 2 file is gone. I must have hit :w2 instead of :wq at some point. :-P

**Comment by matthewsimo** [comment]
@andrewstuart I reviewed and so far it looks good, I'd like to add the corresponding coffeescript and snipmate versions of your work before merging though. I hope I can get to that this weekend, feel free to add those too if you want. :dancer: Stay tuned

**Comment by matthewsimo** [comment]
I've been busy and haven't had a chance to really get to adding the new snippets for the other formats/syntax. I also noticed that there are a few that are already out of sync, so I've decided to go ahead and merge this and then tackle all out of sync snippets in one issue. Thanks for your contribution. :+1:

**Pull request merged**
